# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0014_auto_20170203_1657'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiplayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', jsonfield.fields.JSONField(default=None)),
                ('new_data', jsonfield.fields.JSONField(default=None)),
                ('game_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameSettings')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
