# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('grad_year', models.IntegerField(null=True)),
                ('email_address', models.CharField(max_length=128)),
                ('facebook_url', models.CharField(max_length=128, null=True)),
                ('linkedin_url', models.CharField(max_length=128, null=True)),
                ('curr_location', models.CharField(max_length=128, null=True)),
                ('email_sent', models.NullBooleanField(default=False)),
                ('verified_email', models.NullBooleanField(default=False)),
            ],
        ),
    ]
