# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsitePages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.CharField(max_length=128)),
                ('pathname', models.CharField(max_length=128)),
                ('full_description', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
            ],
        ),
    ]
