# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_websitepages'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepages',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
