# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_websitepages_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitepages',
            name='name',
            field=models.CharField(default=b'unnamed', max_length=128),
        ),
    ]
