# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_websitepages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'unnamed', max_length=128)),
                ('full_url', models.CharField(max_length=128)),
                ('pathname', models.CharField(max_length=128)),
                ('full_description', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.WebsiteCategory')),
            ],
        ),
        migrations.DeleteModel(
            name='WebsitePages',
        ),
    ]
