# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20160509_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'unnamed', max_length=128)),
                ('method', models.CharField(default=b'post', max_length=128)),
                ('action', models.CharField(default=b'/', max_length=128)),
                ('enctype', models.CharField(default=b'application/x-www-form-urlencoded', max_length=128)),
                ('submit_value', models.CharField(default=b'', max_length=128)),
                ('resizeable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='websitepage',
            unique_together=set([('category', 'full_url')]),
        ),
        migrations.AddField(
            model_name='websiteform',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.WebsitePage'),
        ),
        migrations.AlterUniqueTogether(
            name='websiteform',
            unique_together=set([('page', 'name')]),
        ),
    ]
