# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20161013_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitepage',
            name='full_description',
            field=models.CharField(max_length=512),
        ),
    ]
