# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-05 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='dimensions',
            field=jsonfield.fields.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='increasing_factor',
            field=models.DecimalField(decimal_places=4, max_digits=6, null=True),
        ),
    ]
