# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamesettings_tie'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='draw_weights',
            field=models.NullBooleanField(),
        ),
    ]
