# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'games', '0005_auto_20161116_1634'), (b'games', '0006_auto_20161116_1645')]

    dependencies = [
        ('games', '0004_gamesettings_draw_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='capturing_rules',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='pits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='reverse_drawing',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='seeds_per_pit',
            field=models.IntegerField(null=True),
        ),
    ]
