# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20161116_1634_squashed_0006_auto_20161116_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='game_speed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='teleportation_walls',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='max_score',
            field=models.IntegerField(null=True),
        ),
    ]
