# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamesettings_game_speed_squashed_0007_gamesettings_teleportation_walls_squashed_0008_gamesettings_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='multiplayer',
            field=models.NullBooleanField(),
        ),
    ]
