# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gamesettings_multiplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='ai_mode',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gamesettings',
            name='ai_mode2',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
