# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_gamesettings_boulder_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='mine_frequency',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
