# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamesettings_mine_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesettings',
            name='difficulty',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
