# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_gamesettings_draw_style'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamesettings',
            unique_together=set([('user_id', 'game_name')]),
        ),
    ]
